In [39]:
import numpy as np
import pprint as pp

## Matrices and Vectors

In [4]:
x = np.array([[1402, 191],
             [1371, 821],
             [949, 1437],
             [147, 1448]])

y = np.array([[1, 2, 3],
             [4, 5, 6]])

In [5]:
print(x)
print(y)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


In [30]:
print(x.ndim)

2


In [12]:
print(y.ndim)

2


In [13]:
x.size

8

In [14]:
y.size

6

In [15]:
x.shape

(4, 2)

In [16]:
y.shape

(2, 3)

In [25]:
z = np.dot(x, y)
z

array([[ 2166,  3759,  5352],
       [ 4655,  6847,  9039],
       [ 6697,  9083, 11469],
       [ 5939,  7534,  9129]])

In [33]:
z.item(2,2)

11469

## Scalar Addition & Multiplication

In [44]:
A = np.array([[1, 2, 4],
              [5, 3, 2]])
B = np.array([[1, 3, 4],
              [1, 1, 1]])
s = 2

print(A)
print(B)

[[1 2 4]
 [5 3 2]]
[[1 3 4]
 [1 1 1]]


In [45]:
A + B

array([[2, 5, 8],
       [6, 4, 3]])

In [46]:
A - B

array([[ 0, -1,  0],
       [ 4,  2,  1]])

In [47]:
A * B

array([[ 1,  6, 16],
       [ 5,  3,  2]])

In [48]:
A/B

array([[1.        , 0.66666667, 1.        ],
       [5.        , 3.        , 2.        ]])

In [49]:
A//B

array([[1, 0, 1],
       [5, 3, 2]], dtype=int32)

In [51]:
A * s

array([[ 2,  4,  8],
       [10,  6,  4]])

In [52]:
A/s

array([[0.5, 1. , 2. ],
       [2.5, 1.5, 1. ]])

In [53]:
A + s

array([[3, 4, 6],
       [7, 5, 4]])

In [54]:
l = np.array([[1], [4], [2]])
m = np.array([[0], [0], [5]])
n = np.array([[3], [0], [2]])

3 * l + m - n/3

array([[ 2.        ],
       [12.        ],
       [10.33333333]])

## Matrix-Vector Multiplication 

In [56]:
A = np.array([[1,3],[4,0],[2,1]])
v = np.array([[1],[5]])

np.dot(A,v)

array([[16],
       [ 4],
       [ 7]])

In [58]:
A2 = np.array([[1,2,1,5],
               [0,3,0,4],
               [-1,-2,0,0]])
v2 = np.array([[1],
               [3],
               [2],
               [1]])

np.dot(A2,v2)

array([[14],
       [13],
       [-7]])

In [60]:
A3 = np.array([[1,0,3],
               [2,1,5],
               [3,1,2]])
v3 = np.array([[1],
               [6],
               [2]])

np.dot(A3,v3)

array([[ 7],
       [18],
       [13]])

In [63]:
H = np.array([[1,2104],
              [1,1416],
              [1,1534],
              [1, 852]])
h = np.array([[-40],
             [0.25]])

np.dot(H,h)

array([[486. ],
       [314. ],
       [343.5],
       [173. ]])

## Matrix-Matrix Multiplication 

In [64]:
A = np.array([[1,3,2],[4,0,1]])
B = np.array([[1,3],[0,1],[5,2]])

np.dot(A,B)

array([[11, 10],
       [ 9, 14]])

In [65]:
H = np.array([[1,2104],
              [1,1416],
              [1,1534],
              [1, 852]])
h = np.array([[-40,200,-150],
             [0.25,0.1,0.4]])

np.dot(H,h)

array([[486. , 410.4, 691.6],
       [314. , 341.6, 416.4],
       [343.5, 353.4, 463.6],
       [173. , 285.2, 190.8]])

## Inverse & Transpose

In [74]:
from numpy.linalg import inv
import numpy.matlib

In [67]:
A = np.array([[1,2,0],[0,5,6],[7,0,9]])
A

array([[1, 2, 0],
       [0, 5, 6],
       [7, 0, 9]])

In [69]:
A.transpose()

array([[1, 0, 7],
       [2, 5, 0],
       [0, 6, 9]])

In [72]:
A_inv = inv(A)
A_inv

array([[ 0.34883721, -0.13953488,  0.09302326],
       [ 0.3255814 ,  0.06976744, -0.04651163],
       [-0.27131783,  0.10852713,  0.03875969]])

In [73]:
np.dot(A,A_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.11022302e-16,  1.00000000e+00, -1.38777878e-17],
       [ 5.55111512e-17,  2.77555756e-17,  1.00000000e+00]])

In [77]:
I_3 = np.matlib.identity(3)
I_3

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Quiz

In [84]:
u = np.array([[4],[-4],[-3]])
v = np.array([[4],[2],[4]])

In [85]:
u_t = u.transpose()
u_t

array([[ 4, -4, -3]])

In [86]:
np.dot(u_t, v)

array([[-4]])